### PR TITLE
IGVC Backpane 4.0.0 Read For Review

### PR DESCRIPTION
**Pull request by sabinoj**
The IGVC RoboteQ Signal Multiplexer / Blinker Circuit 1.0.0 has no shorts and has passed all of 4PCB's DRCs. This circuit is now ready for review.

### CODE REVIEW

**Comment by sabinoj** [comment]
I would like for Johnny, Zach, and Jasen to review this one to understand how the review process works and how to modify and accept pull requests.

**Comment by sabinoj** [comment]
I am still waiting for a review of both my RoboteQ Signal Multiplexer/Blinker Circuit and the Emergency Stop 3.0.0.

**Comment by l0g1x** [comment]
Any update on this?

**Comment by sabinoj** [comment]
Jasen, if you ever get a moment, could you sit down and look this design over to check for any issues. The sooner this gets done the sooner it can be set up for prototyping in-shop.

**Comment by sabinoj** [comment]
Okay, this pull request has been changed to accommodate a larger project that needs stringent review. I've done a Styrofoam placement test and determined several issues so far.

[ ] Cards are ~0.1" too close to the E-Stop receiver.
[ ] 5V switching regulator connectors are too close together and need to be moved further from the regulator to reduce thermal effects.
[ ] 3.3V switching regulator connectors are too close to the regulator and must be further away.
[ ]  Need to add SPI interfaces near to the Energy Monitor.
[ ] Thermocouple connection is too close to the Energy Monitor it needs to be moved and may need to be upgraded from a two pin to a three pin.
[ ] Design Rule Check for 4PCB standards still needs to be run.
[ ] Need to double check placement of the relay diode.

**Comment by sabinoj** [comment]
The Backplane is ready for another round of reviews.

**Comment by sabinoj** [comment]
The Backplane has been reviewed by Johnny Maltby so far and myself, now I am waiting on Zach's review.

**Comment by sabinoj** [comment]
Review process with Zach Quinn complete this will conclude the review process as soon as a minor task is completed.

**Comment by sabinoj** [comment]
Just ran into an error in the Gerber files. The plated drill is not working correctly the right-most side of the board is being placed far to the left of the Gerber file.

**Comment by sabinoj** [comment]
Determined that the RF transciever socket is backwards.

**Comment by sabinoj** [comment]
Still running into issues with the Gerber files. It turns out that the placement of the drill holes is incorrect and just removing the sign is not enough.

**Comment by sabinoj** [comment]
I just noticed that with the adjustments (removing the negative sign) from the text file I need to re-align the X component of the drill hole to its respective location. The Y component is completely fine.

**Comment by sabinoj** [comment]
The Gerber file has been corrected and double checked. 

Merged Andrew Pable's Ciruit Board repository with this one to verify the Emergency Stop Transmitter 2.0.0 (called Emergency Stop 3.0.0). Review was completed on 05/08/2015 this is being streamlined through the pull process due to time constraints.

**Comment by sabinoj** [comment]
All items in this review have been approved and are to be submitted.

**Pull request merged**
